### ISSUE TITLE
Enable Isolated Marketplaces

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/aquarius#814] opened 2022-06-02 10:38 UTC
Isolated marketplaces are an important feature offering for people planning on forking ocean market and creating their own marketplace. My understanding is that this hasn't been implemented yet. 

It should be possible to set an environmental variable in Aquarius that should lead it to only cache assets that have been signed by a particular address. See [contracts](https://github.com/oceanprotocol/contracts/blob/v4main/contracts/templates/ERC721Template.sol#L279-L292)

**Comment by alexcos20** [comment] 2022-06-21 09:35
duplicate of #813

**Closed by alexcos20** 2022-06-21 09:35 UTC
Labels: Type: Enhancement
