### ISSUE TITLE
Still POA issues

### ISSUE THREAD

**Issue by alexcos20** [oceanprotocol/aquarius#348] opened 2020-12-22 20:19 UTC
taken from aqua rinkeby (  image: oceanprotocol/aquarius:timestamps):

2020-12-22 19:30:32,702 - aquarius.events.events_monitor - DEBUG - get_event_logs (MetadataUpdated, 7765780, 7765781)..
2020-12-22 19:30:33,604 - aquarius.events.metadata_updater - DEBUG - Price/Liquidity monitor >>>> from_block:7765780, current_block:7765781 <<<<
2020-12-22 19:30:36 aquarius-5877b46589-txnnk root[14] INFO running query: {'sort': [{'price.ocean': 'desc'}], 'from': 0, 'size': 9, 'query': {'query_string': {'query': '(price.type:pool) -isInPurgatory:true'
}}}
2020-12-22 19:30:36 aquarius-5877b46589-txnnk root[14] INFO running query: {'sort': [{'created': 'desc'}], 'from': 0, 'size': 9, 'query': {'query_string': {'query': '-isInPurgatory:true'}}}
2020-12-22 19:30:42,545 - aquarius.app.pools - ERROR - pools/history/0x8d3D846597f420eC280dA1E644840d5884c4F0d0: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to
 a POA chain. Refer http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xd983010915846765746889676f312e31342e3130856c696e75
78000000000000d3fde518cc02ed3cdf9765ee4d184610158d9dc8af272970b382285f6f8c539c4badfe56bec7598264f3a83c20333672ca01c93f5cb07cdf3753b4253cf9145300')
Traceback (most recent call last):
  File "/aquarius/aquarius/app/pools.py", line 37, in get_liquidity_history
    ocn_add_remove_list, dt_add_remove_list = ocean.pool.get_liquidity_history(poolAddress)
  File "/usr/local/lib/python3.8/dist-packages/ocean_lib/ocean/ocean_pool.py", line 727, in get_liquidity_history
    timestamps.append(web3.eth.getBlock(b).timestamp)
  File "/usr/local/lib/python3.8/dist-packages/web3/eth.py", line 139, in getBlock
    return self.web3.manager.request_blocking(
  File "/usr/local/lib/python3.8/dist-packages/web3/manager.py", line 109, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/manager.py", line 92, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/gas_price_strategy.py", line 18, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 50, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/attrdict.py", line 18, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 48, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/normalize_errors.py", line 9, in middleware
    result = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/formatting.py", line 57, in apply_formatters
    formatter(response['result']),
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/eth_utils/applicators.py", line 72, in apply_formatter_if
    return formatter(value)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/dist-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/usr/local/lib/python3.8/dist-packages/eth_utils/applicators.py", line 84, in apply_formatters_to_dict
    yield key, formatters[key](item)
  File "/usr/local/lib/python3.8/dist-packages/web3/middleware/validation.py", line 49, in check_extradata_length
    raise ValidationError(
web3.exceptions.ValidationError: The field extraData is 97 bytes, but should be 32. It is quite likely that you are connected to a POA chain. Refer http://web3py.readthedocs.io/en/stable/middleware.html#geth-style-proof-of-authority for more details. The full extraData is: HexBytes('0xd983010915846765746889676f312e31342e3130856c696e7578000000000000d3fde518cc02ed3cdf9765ee4d184610158d9dc8af272970b382285f6f8c539c4badfe56bec7598264f3a83c20333672ca01c93f5cb07cdf3753b4253cf9145300')
2020-12-22 19:30:44,616 - aquarius.events.events_monitor - DEBUG - Metadata monitor >>>> from_block:7765781, current_block:7765782 <<<<

**Comment by calina-c** [comment] 2021-02-02 13:52
See in the definition of:

get_web3_connection_provider in ocean.py

Documentation contains possible fixes.

**Comment by ssallam** [comment] 2021-02-02 14:34
This issue was reported in `https://github.com/ethereum/web3.py/issues/549`
Ocean.py adds a middleware to mitigate this issue.
Check aquarius web3 connection to make sure the middleware is being used to avoid this issue.

**Comment by calina-c** [comment] 2021-02-05 11:11
Closing with Alex's approval since we can not reproduce.

**Closed by calina-c** 2021-02-05 11:11 UTC
Labels: bug, tbd
