### ISSUE TITLE
Fixed rate exchange not detected by aquarius

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#410] opened 2021-03-12 14:58 UTC
For [this asset](https://market.oceanprotocol.com/asset/did:op:43b310151FdCA8A2b0A80D2B9EfC6Ff55b168534) aqua is not detecting any exchange, even though there is one : 0x828f832b84541fd751aef0ff3e23d37d7e9517c2602428e0fa9b2b0f67e2df61

```
[ getExchange(bytes32) method Response ]
  exchangeOwner   address :  0x5241Da498ad8b9AB760467d301556e610F43cB58
  dataToken   address :  0x43b310151FdCA8A2b0A80D2B9EfC6Ff55b168534
  baseToken   address :  0x967da4048cD07aB37855c090aAF366e4ce1b9F48
  fixedRate   uint256 :  50000000000000000000
  active   bool :  true
  supply   uint256 :  1000000000000000000000
```

**Comment by kenbodnar** [comment] 2021-03-18 12:25
This issue is related to aquarius #409 isConsumable not correct. They both go back to the same place in ocean.py. Fixing #409 will solve #410 and vice versa.

**Comment by calina-c** [comment] 2021-04-01 06:55
Isn't this a duplicate of #403?

**Comment by DMats** [comment] 2021-04-02 22:13
Now that #424 is merged, the `exchange_id` is populated correctly.


```
asset['dataToken'] = '0x43b310151FdCA8A2b0A80D2B9EfC6Ff55b168534'
asset['price'] = {'
  address': '',
  'datatoken': 1000.0,
  'exchange_id': '0x828f832b84541fd751aef0ff3e23d37d7e9517c2602428e0fa9b2b0f67e2df61',
  'isConsumable': 'true',
  'ocean': 0.0,
  'pools': [],
  'type': 'exchange',
  'value': 50.0
}
```

**Closed** 2021-04-02 22:18 UTC
Labels: bug, priority:high
