### ISSUE TITLE
`isConsumable` is not correct

### ISSUE THREAD

**Issue by mihaisc** [oceanprotocol/aquarius#409] opened 2021-03-12 13:49 UTC
The property `isConsumable` is not correct and thus the users are not able to consume 

Example : did:op:CbD7aeecB5DFbABaB9126B5Cf1262dCFBA178479 on polygon
```
 "dataTokenInfo": {
    "address": "0xCbD7aeecB5DFbABaB9126B5Cf1262dCFBA178479",
    "name": "Turbulent Swordfish Token",
    "symbol": "TURSWO-35",
    "decimals": 18,
    "totalSupply": 1000,
    "cap": 1000,
    "minter": "0x4D156A2ef69ffdDC55838176C6712C90f60a2285",
    "minterBalance": 1000
  },
  "updated": "2021-03-11T16:16:48Z",
  "accessWhiteList": [],
  "price": {
    "datatoken": 0,
    "ocean": 0,
    "value": 1,
    "type": "exchange",
    "address": "0x2112Eb973af1DBf83a4f11eda82f7a7527D7Fde5",
    "pools": [],
    "isConsumable": "false"
```

**Comment by kenbodnar** [comment] 2021-03-12 14:45
OK I will look at this as well. I just modified the price.address to price.exchange_id, but I haven't pushed it yet.

**Comment by mihaisc** [comment] 2021-03-12 14:46
great, this should be in the same place if i remember correct

**Comment by kenbodnar** [comment] 2021-03-15 20:35
Is there a semantic difference between "totalSupply"  (which is 1000) in the "dataTokenInfo" and the "datatoken" tuple in the price dict? There doesn't seem to be, because the variable assignment for datatoken is dt_supply. 

If so, dt_supply value is not returned properly from _get_fixedrateexchange_price (in metadata_updater.py).  Either it is not getting "owner" or "exchange__id" parameters and they are defaulting to None as they are defined as default in _get_price_updates_from_fixed_rate_exchange.

Tracing it out.

**Comment by kenbodnar** [comment] 2021-03-16 17:10
In line 30 of ocean.py.ocean_lib.web3_internal.contract_handler.py when the _contracts dict is defined, the network alias is hardcoded
30   network_alias = {"ganache": "development"}

It is used in contract_handler.get_contracts_addresses

**Comment by kenbodnar** [comment] 2021-03-22 00:19
This occurs only on the polygon network. With any other network, it works. Here is a rinkeby example:
2021-03-18 18:13:09,006 - aquarius.events.metadata_updater - INFO - updating price info for datatoken: 0x00b43f5905ff736526294ac6de52d1dcd35821c9, pools [], price-info {'datatoken': 999.967, 'ocean': 0.0, 'pools': [], 'value': 1.0, **'isConsumable': 'true',**

This would suggest a network configuration error rather than an aquarius bug. I did not connect to polygon as it is a production environment, and didn't have the config parameters.

**Comment by mihaisc** [comment] 2021-03-22 09:59
Other examples from eth mainnet
https://market.oceanprotocol.com/asset/did:op:177bf5F3cbdDeB80714440A36B79d454E4156A19 - totalSupply 1000 ,isConsumable false
https://market.oceanprotocol.com/asset/did:op:A6b6A1a093047511A12D8BF8f91Aa9Cd51c57ECC - totalSupply 1000 ,isConsumable false

**Comment by kenbodnar** [comment] 2021-03-22 12:31
Interesting. The only logic to determine is_consumable is supply is not None and supply > 1. Seems straight forward enough. That's it for aquarius code.

**Comment by kenbodnar** [comment] 2021-03-22 12:39
The only other logical explanation is that there is a delta between total supply and the supply fetched by the ocean.py contract handler. If the supply has been consumed then is_consumable is correctly false. But if that is the case, then total supply is a historical artifact and not the complete picture of the returned metadata. Checking it out.

**Comment by kenbodnar** [comment] 2021-03-22 14:14
OK figured it out. It correctly sets the isConsumable from the get_fixedrate_exchange, but the isConsumable flag is not being set properly from get_price_updates_from liquidity where it gets price updates from the pools.

**Comment by kenbodnar** [comment] 2021-03-23 00:50
It turns out that Aquarius was right all along.  I checked the two examples given, on Ethereum mainnet and looked at the token contracts. There is no price information in the contract. The logic in Aquarius is that price is not None and price > 0.  In the contracts on the mainnet, there is no price. I checked it on etherscan.io. See for yourself:
The Fantastic Eel token:
https://etherscan.io/token/0x177bf5f3cbddeb80714440a36b79d454e4156a19?a=0x262a4f11ab1446ca8ea160cd2fc549051b6cb330

Overview [ERC-20]
PRICE
$0.0000 @ 0.000000 Eth
FULLY DILUTED MARKET CAP 
$0.00
Max Total Supply:
1,000 FANEEL-7


Taciturn Seal Token
https://etherscan.io/token/0xA6b6A1a093047511A12D8BF8f91Aa9Cd51c57ECC
PRICE
$0.0000 @ 0.000000 Eth
FULLY DILUTED MARKET CAP 
$0.00
Max Total Supply:
1,000 TACSEA-32

There is only 1 Holder in both cases.

**Comment by DMats** [comment] 2021-04-01 03:17
I started working on this issue today. With @calina-c 's help, I was able to set up a debug environment. I've successfully reproduced the bug. The following screenshot shows the moment where `is_consumable` is set to `false` for the FANEEL-7 token, one of the tokens mentioned by @mihaisc in his previous comment https://github.com/oceanprotocol/aquarius/issues/409#issuecomment-803933209.  As you can see, the reason it comes up false is that the price is $0. I'll dive further into it tomorrow.

![Screenshot from 2021-03-31 23-15-56.png](https://images.zenhubusercontent.com/604f6e0302390d3e079501ce/a8673879-158c-4ba9-a30f-28847cca9a3f)

**Comment by DMats** [comment] 2021-04-01 16:33
@mihaisc what is the desired behavior of `isConsumable` just so I'm clear on what I'm trying to achieve.

**Comment by mihaisc** [comment] 2021-04-01 18:24
This was the first issue, it's explained based on functions from ocean.js . Some may not exist in ocean.py

https://github.com/oceanprotocol/aquarius/issues/331

**Comment by alexcos20** [comment] 2021-04-06 12:06
we are going to ditch this flag, so closing it for now

**Closed by alexcos20** 2021-04-06 12:06 UTC
Labels: bug, priority:high

**Comment by DMats** [comment] 2021-04-06 16:11
Should we create an issue to remove `is_consumable` from aquarius?
