### ISSUE TITLE
Unable to connect Aquarius with Market on Polygon testnet

### ISSUE THREAD

**Issue by umang-usquare** [oceanprotocol/aquarius#915] opened 2022-10-10 10:09 UTC
Hi there!

I am trying to run Aquarius for Polygon Mumbai network and am facing the following issue:

- Aquarius is not indexing the blocks and storing on elastic search for the Polygon Mumbai network.

The following changes have been made in the example file, "aquarius-events-rinkeby-deployment.yaml":

- DB_HOSTNAME
- EVENTS_RPC (Value set to IPFS project id for Polygon Mumbai network). This is RPC URL and not Web Socket URL.

Really eager to solve this issue as it is blocking my further development on Ocean protocol.

**Comment by AnaLoznianu** [comment] 2022-10-11 07:33
Hello, thanks for reporting this issue! I can confirm there is an issue with aqua. We are currently investigating it

**Comment by AnaLoznianu** [comment] 2022-10-21 09:07
Hello :) The issue is now fixed. Aqua was stuck in a loop due to some processing errors.

**Closed by AnaLoznianu** 2022-10-21 09:07 UTC
Labels: Type: Bug, Priority: High
